ENGG-7112 Migrate to https://software.kontakt.io/public/portal/dev.bin
kontaktio/software-py-tools pull request #8
Opened 2022-08-02 09:51 UTC by vpanovk

2022-08-02 11:50 UTC, koriit-kontakt requested changes

2022-08-02 11:50 UTC, koriit-kontakt commented on mass_configure_pl.py
> +                model='PORTAL_LIGHT'
I think we should look for only provisioned devices. Because only they can actually download and apply configs.

2022-08-02 12:44 UTC, vpanovk commented on mass_configure_pl.py
> +                model='PORTAL_LIGHT'
How can I tell between provisioned and non-provisioned ones? 
I could think of 2 options:
* check for whitelisted param - but older PL firmwares didn't set it to false post-provisioning
* check for certain `applications.system` keys that would be set during provisioning, like otaUrl and dataHost - but again, any of those could've been set under different circumstances.
Therefore I settled for all PLs - because there's only around 8k of them, and unneeded pending config won't do any harm - so it's better to cover too much than hit and miss.

2022-08-02 14:17 UTC, koriit-kontakt commented on mass_configure_pl.py
> +                model='PORTAL_LIGHT'
What about checking against "assigned" field at the very least? assigned=false means unclaimed and such a device is rather unprovisioned.

2022-08-02 18:14 UTC, vpanovk commented on mass_configure_pl.py
> +                model='PORTAL_LIGHT'
Yeah, this one sounds surefire :) I'll add that condition to SQL query.

2022-08-02 18:49 UTC, vpanovk commented on mass_configure_pl.py
> +                model='PORTAL_LIGHT'
Alrighty, now we're down to just 6898 PLs!

2022-08-03 07:03 UTC, proszczyniala-kontaktio requested changes

2022-08-03 07:03 UTC, proszczyniala-kontaktio commented on mass_configure_pl.py
> +    conn = psycopg2.connect(
Connection is not closed.

2022-08-03 07:03 UTC, proszczyniala-kontaktio commented on mass_configure_pl.py
> +import logging
1. I miss some documentation that describes what this script is for and how to use it. 
2. Is it a one-time script (execute and remove)?

2022-08-03 07:03 UTC, proszczyniala-kontaktio commented on mass_configure_pl.py
> +                 join manager m on d.manager_id = m.id
Just checking - Is `join` enough or should we use `left join`? So - the relation between device and manager always exists or not?

2022-08-03 08:50 UTC, vpanovk commented on mass_configure_pl.py
> +import logging
Yep, I designed this repo as a collection of fire-once-and-forget scripts. They're all as simple as possible to the extent of not really needing documentation. There's supposed to be a brief description for each of them in README that I forgot to add though.

2022-08-03 08:52 UTC, vpanovk commented on mass_configure_pl.py
> +                 join manager m on d.manager_id = m.id
Join is okay since we can skip devices that are not associated with any manager. Our target are PLs that are provisioned and owned by a certain account (i.e. manager).

2022-08-03 08:53 UTC, merged